Poprawki, folder imienny i zadania z dzialu2
t0meck-pj/ukos2023-24_12c pull request #15
Opened 2023-12-16 10:03 UTC by s31321-pj

2024-01-16 17:36 UTC, t0meck-pj requested changes
Proszę poprawić wskazane rzeczy i dosłać te poprawki do aktualnego PR. Nie tworzyć nowego PR.

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/.gitignore
Proszę nie przenosić plików spoza swojego katalogu

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/README.md
Proszę nie przenosić plików spoza swojego katalogu

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/t0meck-pj-TomaszIdzikowski/pamietnik.txt
Proszę nie przenosić plików spoza swojego katalogu

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/1_Linux_Wstęp_do_konsoli/Drugi_zestaw_zadań.txt
> +
Zbędne interlinie

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/1_Linux_Wstęp_do_konsoli/Drugi_zestaw_zadań.txt
> +usunie wszystkie pliki z katalogu a następnie kataloh.
katalo[h]

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/1_Linux_Wstęp_do_konsoli/Pamietnik_1.txt
1. Proszę dodać do pamiętnika datę wpisu
2. Pamiętnik powinien być bezpośrednio w Twoim katalogu a nie głębiej (w katalogu konkretnych zajęć) - proszę zobaczyć jak to jest w moim katalogu

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/1_Linux_Wstęp_do_konsoli/Pierwszy_zestaw_zadań.txt
> +Angielska wesja językowa, dlatego zamiast Pulpit przechodzę do Desktop.
👍

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/2_Uprawnienia_dostepu/ZADANIA.txt
> +Polecenie chmod możemy wykonać w katalogu bieżącym do którego mamy uprawnienia, w przypadku braku uprawnien nie będziemy w stanie wydać polecenia zmiany uprawnień.
Jakie uprawnienia są wymagane?

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/2_Uprawnienia_dostepu/ZADANIA.txt
> +Nie możemy wrócić do katalogu nadrzędnego do którego uprawnień nie mamy.
Nie o to chodziło. Jeśli się wyjdzie z XYZ np. ścieżką bezwzględną to czy potem `cd -` powrócimy do XYZ pomimo, że nie mamy dostępu do ABC ?

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/2_Uprawnienia_dostepu/ZADANIA.txt
> +
Zbędne interlinie

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/2_Uprawnienia_dostepu/ZADANIA.txt
> +pliku strona.html, aby zawartość pliku była widoczna w przeglądarce internetowej pod adresem http://szuflandia.pjwstk.edu.pl/~twój_login/strona.html
A gdzie odpowiedzi na pytania?

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_0.txt
> +są wszystkie nazwy plików, które zawierają literkę D (oczytałem plik
oczytałem

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_1.txt
> +
Zbędne interlinie

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_1.txt
> +Brak uprawnień do wyświetlenia tej infromacji
Nie. To nie to. Szukaj dalej tej "infromacji"

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_1.txt
> +Użyłem "ps axu | grep root"
Jeśli user "Jakub" uruchomi proces `i_am_groot` to powyższe polecenie także go wypisze

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_1.txt
> +Użyję polecenia "ps axu"
Mało. Do poprawy.

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_2.txt
> +Uruchomiłem vim
czy `vim` jest programem graficznym tj wymagającym środowiska graficznego do wyświetlenia jego okna?

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania.txt
> +
zbędne interlinie

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania.txt
> +5
A gdzie rozwiązanie zadania?

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania.txt
> +chmod u=,g=,o= zasob
można łączyć ze sobą literki poza tym jest także literka `a` oznaczenie "all"

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania.txt
> +ls | tee plik.txt
np. nie używając dedykowanego polecenia do listowawnia zawartości katalogów...
A w odpowiedzi co?
`ls`

2024-01-16 17:36 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania_1_9.txt
Proszę nie dodawać pustych plików.

2024-02-03 00:57 UTC, s31321-pj commented on s31321-JakubTrzaskowski/.gitignore
Plik usunięty

2024-02-03 00:57 UTC, s31321-pj commented on s31321-JakubTrzaskowski/README.md
Plik usunięty

2024-02-03 00:57 UTC, s31321-pj commented on s31321-JakubTrzaskowski/t0meck-pj-TomaszIdzikowski/pamietnik.txt
Plik usunięty

2024-02-03 00:57 UTC, s31321-pj commented on s31321-JakubTrzaskowski/1_Linux_Wstęp_do_konsoli/Drugi_zestaw_zadań.txt
> +
Interlinie usunięte

2024-02-03 00:57 UTC, s31321-pj commented on s31321-JakubTrzaskowski/1_Linux_Wstęp_do_konsoli/Drugi_zestaw_zadań.txt
> +usunie wszystkie pliki z katalogu a następnie kataloh.
Poprawione

2024-02-03 00:58 UTC, s31321-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania.txt
> +
Interlinie usunięte

2024-02-03 00:58 UTC, s31321-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania.txt
> +chmod u=,g=,o= zasob
poprawione

2024-02-03 00:58 UTC, s31321-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania.txt
> +ls | tee plik.txt
dodana odpowiedź z wykorzystaniem echo

2024-02-03 00:58 UTC, s31321-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania_1_9.txt
plik usunięty

2024-02-03 01:32 UTC, s31321-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_0.txt
> +są wszystkie nazwy plików, które zawierają literkę D (oczytałem plik
poprawione

2024-02-03 01:33 UTC, s31321-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_1.txt
> +
poprawione

2024-02-03 01:35 UTC, s31321-pj commented on s31321-JakubTrzaskowski/2_Uprawnienia_dostepu/ZADANIA.txt
> +
poprawione

2024-02-03 22:21 UTC, t0meck-pj commented
> Proszę poprawić wskazane rzeczy i dosłać te poprawki do aktualnego PR. Nie tworzyć nowego PR.

2024-02-03 22:27 UTC, t0meck-pj approved these changes
Warunkowo to zatwierdzę bo nie chce mi się kolejny raz tego czytać.
Popraw błędy i dopiero teraz otwórz nowy PR.

2024-02-03 22:27 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/Pamietnik_1.txt
> +bezwzględnej.
Jeden wpis przez cały semestr? A gdzie reszta?
No i gdzie daty wpisów o które prosiłem wcześniej?

2024-02-03 22:27 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/4_Kolokwium_Powtórzenie/Zadania.txt
> +chmod u=,g=,o= zasob
Gdzie? bo nie widzę

2024-02-03 22:27 UTC, t0meck-pj commented on s31321-JakubTrzaskowski/3_Procesy_i_Strumienie/Zadania_1.txt
> +
Gdzie? bo ja nadal widzę zbędne interlinie tu pomiędzy poleceniami.

2024-02-03 22:27 UTC, merged