Zadania
t0meck-pj/ukos2023-24_12c pull request #22
Opened 2024-02-04 04:23 UTC by s30900-pj

2024-02-04 04:34 UTC, t0meck-pj requested changes
Proszę wybaczyć ale nie będę czytał dalej tego PR. Jest w nim tyle błędów... jakby jakiś automat próbował poprawić treści plików. Proszę samemu sprawdzić i przeczytać swoje pliki. Sprawdzić składnię poleceń oraz czy zdania są napisane po polsku bo aktualne zmiany na to nie wskazują.

Trochę szacunku dla swojego recenzenta!
Ktoś poświęca czas na sprawdzenie Waszych zmian. PR wysyła się dopiero wtedy gdy jest się pewnym, że to co jest wysyłane jest wolne od błędów a mimo wszystko samemu także powinno się sprawdzić czy jeszcze gdzieś jakiś błędów nie ma przeglądając podsumowanie PR przed jego finalnym wysłaniem.

Tymczasem PR zamykam.

2024-02-04 04:34 UTC, t0meck-pj commented on s30900-Pawel_Kozlowski/Zadania/2.Linux - Uprawnienia dostępu.txt
> +   Czy można bezpośrednio przeskoczyć do katalogu ABC/XYZ, jeśli nie mamy licencji wstępnej do ABC, ale mamy do XYZ?
Co to ma być? Zadanie brzmiało inaczej.
Co to jest licencja wstępna?

2024-02-04 04:34 UTC, t0meck-pj commented on s30900-Pawel_Kozlowski/Zadania/2.Linux - Uprawnienia dostępu.txt
> +   Gdy używamy bezwzględnego ścieżki dostępu do katalogu głównego, pomijamy katalog, do którego nie mamy dostępu.
To zdanie nie ma składu.
Poprzednie było lepsze choć zawierało błędy ortograficzne.

2024-02-04 04:34 UTC, t0meck-pj commented on s30900-Pawel_Kozlowski/Zadania/2.Linux - Uprawnienia dostępu.txt
> +   Czy można również usunąć z polecenia cd -? Wróciliśmy do XYZ, nie mogliśmy przejść do ABC z
> Czy można usunąć z polecenia cd - ?

Co to ma być? Skąd te zmiany treści zadań?

2024-02-04 04:34 UTC, t0meck-pj commented on s30900-Pawel_Kozlowski/Zadania/2.Linux - Uprawnienia dostępu.txt
> +   Które są dostępne dla dostępu, które należą do katalogu domowego;
masło maślane

2024-02-04 04:34 UTC, t0meck-pj commented on s30900-Pawel_Kozlowski/Zadania/3.Linux - Procesy i Strumienie.txt
> +   - osłona zx lub bez niego jest taka, że: bez niego do wyświetlania wszystkich terminali
osłona?

2024-02-04 04:35 UTC, closed without merging

2024-02-05 10:54 UTC, s30900-pj commented
Witam. Powodem zmienionych pytań jest moja głupota gdyż myślałem przy
sprawdzaniu błędów przez pana do mnie wysłanych że je źle przepisałem, a
okazało się że strona na google mi przetłumaczyła pana odpowiedź co mnie
zmyliło o późnej porze. Myślę że aktualnie powinno być dobrze  wysłałem
commita przed wysłaniem postarałem się poprawić błędy jakie pan znalazł
oraz jakie sam znalazłem. Chciałbym żeby moja praca była zaakceptowana wiec
jeśli są jeszcze jakieś błędy to poprawię. A i żaden automat nie próbował
poprawić treści plików. ;)

niedz., 4 lut 2024 o 05:35 t0meck-pj ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
>
> Proszę wybaczyć ale nie będę czytał dalej tego PR. Jest w nim tyle
> błędów... jakby jakiś automat próbował poprawić treści plików. Proszę
> samemu sprawdzić i przeczytać swoje pliki. Sprawdzić składnię poleceń oraz
> czy zdania są napisane po polsku bo aktualne zmiany na to nie wskazują.
>
> Trochę szacunku dla swojego recenzenta!
> Ktoś poświęca czas na sprawdzenie Waszych zmian. PR wysyła się dopiero
> wtedy gdy jest się pewnym, że to co jest wysyłane jest wolne od błędów a
> mimo wszystko samemu także powinno się sprawdzić czy jeszcze gdzieś jakiś
> błędów nie ma przeglądając podsumowanie PR przed jego finalnym wysłaniem.
>
> Tymczasem PR zamykam.
> ------------------------------
>
> In s30900-Pawel_Kozlowski/Zadania/2.Linux - Uprawnienia dostępu.txt
> <https://github.com/t0meck-pj/ukos2023-24_12c/pull/22#discussion_r1477175314>
> :
>
> >     ***@***.***:~/katalog$ chmod u+r,u+w,u+x zadania
>
> -   Czy możemy bezpośrednio przeskoczyć do katalogu ABC/XYZ, jeśli nie mamy uprawnienia wstępu do ABC, ale mamy do XYZ ?
> +   Czy można bezpośrednio przeskoczyć do katalogu ABC/XYZ, jeśli nie mamy licencji wstępnej do ABC, ale mamy do XYZ?
>
> Co to ma być? Zadanie brzmiało inaczej.
> Co to jest licencja wstępna?
> ------------------------------
>
> In s30900-Pawel_Kozlowski/Zadania/2.Linux - Uprawnienia dostępu.txt
> <https://github.com/t0meck-pj/ukos2023-24_12c/pull/22#discussion_r1477175348>
> :
>
> >
> -   gdy urzyjemy ścieżki bezwzględnej to możemy przejść do katalogu ponieważ omijamy katalog Do którego nie mamy dostępu
> -   ścieżka względna by wypisała błąd ponieważ nie mamy dostępu przejść przez katalog ABC
> +   Gdy używamy bezwzględnego ścieżki dostępu do katalogu głównego, pomijamy katalog, do którego nie mamy dostępu.
>
> To zdanie nie ma składu.
> Poprzednie było lepsze choć zawierało błędy ortograficzne.
> ------------------------------
>
> In s30900-Pawel_Kozlowski/Zadania/2.Linux - Uprawnienia dostępu.txt
> <https://github.com/t0meck-pj/ukos2023-24_12c/pull/22#discussion_r1477175540>
> :
>
> >
> -   Czy możemy także wrócić korzystając z polecnia cd - ?
> -   możemy wrócic jedynie do XYZ, nie możemy do ABC ponieważ nie mamy uprawnień
> +   Czy można również usunąć z polecenia cd -? Wróciliśmy do XYZ, nie mogliśmy przejść do ABC z
>
> Czy można usunąć z polecenia cd - ?
>
> Co to ma być? Skąd te zmiany treści zadań?
> ------------------------------
>
> In s30900-Pawel_Kozlowski/Zadania/2.Linux - Uprawnienia dostępu.txt
> <https://github.com/t0meck-pj/ukos2023-24_12c/pull/22#discussion_r1477175566>
> :
>
> > @@ -106,7 +105,7 @@
>     </BODY>
>     </HTML>
>
> -   Sprawdzić, jakie są minimalne uprawnienia dostępu, które trzeba przydzielić do katalogu domowego;
> +   Które są dostępne dla dostępu, które należą do katalogu domowego;
>
> masło maślane
> ------------------------------
>
> In s30900-Pawel_Kozlowski/Zadania/3.Linux - Procesy i Strumienie.txt
> <https://github.com/t0meck-pj/ukos2023-24_12c/pull/22#discussion_r1477175615>
> :
>
> > @@ -137,18 +137,18 @@ Zadanie 1
>
>     Jak myślisz, co oznacza znak zapytania w kolumnie 2?(wiedziałem)
>     - dany proces nie ma nadanego terminala
> -   - różnica z x lub bez niego jest taka że: bez niego to wyuświetla wszystkie które mają terminal
> +   - osłona zx lub bez niego jest taka, że: bez niego do wyświetlania wszystkich terminali
>
> osłona?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/t0meck-pj/ukos2023-24_12c/pull/22#pullrequestreview-1861263301>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BC6BDP22O6JXBUM7AFPGJC3YR4FX3AVCNFSM6AAAAABCYROZWWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRRGI3DGMZQGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>