zadania z kolokwium-powtorzenie i uprawnienia-dostepu
t0meck-pj/ukos2023-24_12c pull request #7
Opened 2023-11-29 23:44 UTC by s30576-pj

2023-12-01 04:55 UTC, t0meck-pj requested changes
Za dużo tu błędów by to puścić dalej. Do poprawy.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    cd ../../ala/ma/ale
Chyba musze zmienić treść zadania...
Jak przejść do katalogu `ala` LECZ za pomocą...

Poza tym ścieżka jest błędna tak czy inaczej. Do poprawy.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    cd /tmp/ukos/ala/ma/ale
jw.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    mkdir -p ../../ala/ma/ale/jan/kowalski
jw

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    mkdir -p /tmp/ukos/ala/ma/ale/jan/kowalski
jw

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    mv ../../ala ../../i
jw.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    mv /tmp/ukos/ala /tmp/ukos/ala/i
jw.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +kill %1
do poprawy. To jest błędna składnia.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +ls -l al*
To zwróci także katalogi. Do poprawy.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +ls -l | grep '^al'
jw.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +uprawnienia dla katalogu ala to 755 (rwxr-xr-x)
Błędnie wyliczone bity. Do poprawy.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    chmod 711 ala
jw. + błędna ścieżka

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    chmod u=rwx,go= ala
do poprawy

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +    chmod u+rwx,go= ala
do poprawy

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_procesy_i_strumienie.txt
> +natan@natan-virtual-machine:~$ ps
No! Teraz ma to sens.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_procesy_i_strumienie.txt
>  rozumiem to tak ze w pierwszym przykladnie po wpisaniu witaj gdzy kliknalem
gdzy

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_uprawnienia_dostepu.txt
> +	(cd /sciezka/do/ABC/XYZ)
możemy?

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_uprawnienia_dostepu.txt
> +	wrocic do niego za pomocą polecenia cd -. To polecenie nie wymaga specjalnych
hmm... w połączeniu z powyższym także?

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_uprawnienia_dostepu.txt
> +chmod 711 ~  						--> minimalne uprawnienia do katalogu domowego, uzytkownik ma pelne uprawnienia, ale inni tylko dostep do katalogu
Minimalne to dosłownie minimalne. Użytkownik/właściciel nie potrzebuje mieć dostępu. Grupa także.

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_uprawnienia_dostepu.txt
> +chmod 755 public_html  				--> minimalne uprawnienia do katalogu public_html, uzytkownik ma pełne uprawnienia, a inni tylko do odczytu i wykonania
do poprawy

2023-12-01 04:55 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_uprawnienia_dostepu.txt
> +chmod 644 public_html/strona.html  	--> minimalne uprawnienia do pliku, uzytkownik ma pelne uprawnienia, a inni tylko do odczytu
do poprawy

2023-12-01 22:06 UTC, s30576-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +uprawnienia dla katalogu ala to 755 (rwxr-xr-x)
rwx --> 111 --> 7
r-x --> 101 --> 5
chyba ze dalej sie myle

2023-12-01 22:54 UTC, s30576-pj commented
wrzucone poprawki

2023-12-02 02:15 UTC, t0meck-pj approved these changes

2023-12-02 02:15 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +ls -l al* | grep -v /
Lepiej ale ten slash to sam się tam magicznie nie pojawi. Trzeba do `ls` coś jeszcze dodać

2023-12-02 02:15 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +ls -l | grep '^-' | grep 'al'
A jeśli pliki by były własnością użytkownika `alf` ?
Szukamy rozwiązania generycznego pasującego w każdej sytuacji.

2023-12-02 02:15 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_kolokwium_powtorzenie.txt
> +uprawnienia dla katalogu ala to 755 (rwxr-xr-x)
Błąd jest w others.

2023-12-02 02:15 UTC, t0meck-pj commented on s30576-pj-NatanBrzozowski/zad_uprawnienia_dostepu.txt
> +	(/sciezka/do/ABC/XYZ), jeśli brakuje uprawnień do katalogu ABC. Prawa dostępu
Prawa do systemu.
Uprawnienia do zasobu.

2023-12-02 02:15 UTC, merged